### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by rarslan** [rarslan/PHP-MVC-RESTful-API#1]
The things that should be improved:

- [ ] Better routing (to add YAML would be a possibility)
- [ ] The controllers should be more abstract
- [ ] Adding more error handlers
- [ ] More stylish errors
- [ ] Unit Testing
- [ ] Paying someone to review it in order to make it better
